#!/usr/bin/env bash

set -e

sudo apt-add-repository ppa:numix/ppa -y
sudo apt-get update
sudo apt-get -y install numix-icon-theme-circle
sudo dpkg -i Themes/royal-gtk-theme_1.0-1_all.deb

echo "Installation is done"
echo "Change theme to Royal and icons to Numix"
